//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendenceSheet
    {
        public int AttendenceSheetID { get; set; }
        public System.DateTime ClockInTime { get; set; }
        public Nullable<System.DateTime> ClockOutTime { get; set; }
        public int FarmWorkerNum { get; set; }
        public int UserID { get; set; }
    
        public virtual FarmWorker FarmWorker { get; set; }
        public virtual User User { get; set; }
    }
}
