//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiologicalDisaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BiologicalDisaster()
        {
            this.FieldBiologicalDisasters = new HashSet<FieldBiologicalDisaster>();
        }
    
        public int BioDisasterID { get; set; }
        public string BioDisasterDescr { get; set; }
        public string BioDisasterNotes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldBiologicalDisaster> FieldBiologicalDisasters { get; set; }
    }
}
