//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmWorker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FarmWorker()
        {
            this.AttendenceSheets = new HashSet<AttendenceSheet>();
        }
    
        public int FarmWorkerNum { get; set; }
        public string FarmWorkerFName { get; set; }
        public string FarmWorkerLName { get; set; }
        public string FarmWorkerContactNum { get; set; }
        public string FarmWorkerImg { get; set; }
        public string Address { get; set; }
        public string Surburb { get; set; }
        public string City { get; set; }
        public int CountryID { get; set; }
        public int ProvinceID { get; set; }
        public System.DateTime ContractStartDate { get; set; }
        public System.DateTime ContractEndDate { get; set; }
        public string FarmWorkerIDNum { get; set; }
        public int TitleID { get; set; }
        public int GenderID { get; set; }
        public int FarmWorkerTypeID { get; set; }
        public int FarmID { get; set; }
        public Nullable<bool> ClockedIn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendenceSheet> AttendenceSheets { get; set; }
        public virtual Country Country { get; set; }
        public virtual Farm Farm { get; set; }
        public virtual FarmWorkerType FarmWorkerType { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Province Province { get; set; }
        public virtual Title Title { get; set; }
    }
}
