//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmWorkerType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FarmWorkerType()
        {
            this.FarmWorkers = new HashSet<FarmWorker>();
        }
    
        public int FarmWorkerTypeID { get; set; }
        public string FarmWorkerTypeDescr { get; set; }
        public string FarmWorkerTypeNotes { get; set; }
        public string FarmWorkerTypeActiveStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FarmWorker> FarmWorkers { get; set; }
    }
}
