//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmLogin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FarmDbContext : DbContext
    {
        public FarmDbContext()
            : base("name=FarmDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AttendenceSheet> AttendenceSheets { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<AuditType> AuditTypes { get; set; }
        public virtual DbSet<BiologicalDisaster> BiologicalDisasters { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CropCycle> CropCycles { get; set; }
        public virtual DbSet<CropType> CropTypes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Farm> Farms { get; set; }
        public virtual DbSet<FarmWorker> FarmWorkers { get; set; }
        public virtual DbSet<FarmWorkerType> FarmWorkerTypes { get; set; }
        public virtual DbSet<Field> Fields { get; set; }
        public virtual DbSet<FieldBiologicalDisaster> FieldBiologicalDisasters { get; set; }
        public virtual DbSet<FieldNaturalDisaster> FieldNaturalDisasters { get; set; }
        public virtual DbSet<FieldStage> FieldStages { get; set; }
        public virtual DbSet<FieldStatu> FieldStatus { get; set; }
        public virtual DbSet<FieldTreatment> FieldTreatments { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<InventoryTreatment> InventoryTreatments { get; set; }
        public virtual DbSet<InventoryType> InventoryTypes { get; set; }
        public virtual DbSet<Land> Lands { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<NaturalDisaster> NaturalDisasters { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderLine> OrderLines { get; set; }
        public virtual DbSet<OrderStatu> OrderStatus { get; set; }
        public virtual DbSet<Plantation> Plantations { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<RainfallRecord> RainfallRecords { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Silo> Silos { get; set; }
        public virtual DbSet<SiloHarvest> SiloHarvests { get; set; }
        public virtual DbSet<SiloHarvestSale> SiloHarvestSales { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<Treatment> Treatments { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserAccessLevel> UserAccessLevels { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<VehicleMake> VehicleMakes { get; set; }
        public virtual DbSet<VehicleService> VehicleServices { get; set; }
        public virtual DbSet<VehicleType> VehicleTypes { get; set; }
    }
}
