//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Field()
        {
            this.FieldBiologicalDisasters = new HashSet<FieldBiologicalDisaster>();
            this.FieldNaturalDisasters = new HashSet<FieldNaturalDisaster>();
            this.FieldTreatments = new HashSet<FieldTreatment>();
            this.Plantations = new HashSet<Plantation>();
        }
    
        public int FieldID { get; set; }
        public string FieldName { get; set; }
        public decimal FieldHectares { get; set; }
        public int FieldStatusID { get; set; }
        public int LandID { get; set; }
    
        public virtual FieldStatu FieldStatu { get; set; }
        public virtual Land Land { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldBiologicalDisaster> FieldBiologicalDisasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldNaturalDisaster> FieldNaturalDisasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldTreatment> FieldTreatments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantation> Plantations { get; set; }
    }
}
