//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryTreatment
    {
        public int TreatmentID { get; set; }
        public int InventoryID { get; set; }
        public int TreatmentQnty { get; set; }
        public int Unit { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Treatment Treatment { get; set; }
        public virtual Unit Unit1 { get; set; }
    }
}
