//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int OrderNum { get; set; }
        public int InventoryID { get; set; }
        public decimal OrderLineTotalAmount { get; set; }
        public int OrderLineTotalQuantity { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Order Order { get; set; }
    }
}
