//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plantation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plantation()
        {
            this.SiloHarvests = new HashSet<SiloHarvest>();
        }
    
        public int PlantationID { get; set; }
        public int FieldID { get; set; }
        public int CropTypeID { get; set; }
        public int CropCycleID { get; set; }
        public int FieldStageID { get; set; }
        public System.DateTime DatePlanted { get; set; }
        public Nullable<decimal> RefugeSeedAmntUsed { get; set; }
        public Nullable<int> RefugeUnit { get; set; }
        public Nullable<decimal> RefugeAreaHectares { get; set; }
        public decimal ExpectedYieldQnty { get; set; }
        public int YieldUnit { get; set; }
        public Nullable<System.DateTime> DateHarvested { get; set; }
        public string PlantationStatus { get; set; }
    
        public virtual CropCycle CropCycle { get; set; }
        public virtual CropType CropType { get; set; }
        public virtual Field Field { get; set; }
        public virtual FieldStage FieldStage { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiloHarvest> SiloHarvests { get; set; }
    }
}
