//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RainfallRecord
    {
        public int RainFallRecID { get; set; }
        public System.DateTime RecordDate { get; set; }
        public int RecordMeasurement { get; set; }
        public int UnitID { get; set; }
        public int LandID { get; set; }
    
        public virtual Land Land { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
