//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace farmLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.VehicleServices = new HashSet<VehicleService>();
        }
    
        public int VehicleID { get; set; }
        public string VehName { get; set; }
        public string VehYear { get; set; }
        public string VehModel { get; set; }
        public string VehEngineNum { get; set; }
        public string VehVinNum { get; set; }
        public string VehRegNum { get; set; }
        public string VehLicenseNum { get; set; }
        public System.DateTime VehExpDate { get; set; }
        public int VehCurrMileage { get; set; }
        public int VehServiceInterval { get; set; }
        public int UnitID { get; set; }
        public int VehNextService { get; set; }
        public int Farm { get; set; }
        public int VehTypeID { get; set; }
        public int VehMakeID { get; set; }
    
        public virtual Farm Farm1 { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual VehicleMake VehicleMake { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleService> VehicleServices { get; set; }
    }
}
